/* automatically generated by rust-bindgen */

pub const MINIMP3_MAX_SAMPLES_PER_FRAME: ::std::os::raw::c_uint = 2304;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mp3dec_frame_info_t {
    pub frame_bytes: ::std::os::raw::c_int,
    pub channels: ::std::os::raw::c_int,
    pub hz: ::std::os::raw::c_int,
    pub layer: ::std::os::raw::c_int,
    pub bitrate_kbps: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct mp3dec_t {
    pub mdct_overlap: [[f32; 288usize]; 2usize],
    pub qmf_state: [f32; 960usize],
    pub reserv: ::std::os::raw::c_int,
    pub free_format_bytes: ::std::os::raw::c_int,
    pub header: [::std::os::raw::c_uchar; 4usize],
    pub reserv_buf: [::std::os::raw::c_uchar; 511usize],
}
extern "C" {
    pub fn mp3dec_init(dec: *mut mp3dec_t);
}
extern "C" {
    pub fn mp3dec_decode_frame(
        dec: *mut mp3dec_t,
        mp3: *const ::std::os::raw::c_uchar,
        mp3_bytes: ::std::os::raw::c_int,
        pcm: *mut ::std::os::raw::c_short,
        info: *mut mp3dec_frame_info_t,
    ) -> ::std::os::raw::c_int;
}
